services:
  zipkin-client:
    image: ghcr.io/openzipkin/zipkin-slim:latest
    container_name: zipkin-client
    restart: always
    ports:
      - 9411:9411

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    restart: always
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317
      - 1888:1888 # pprof extension
      - 13133:13133 # health_check extension

  service-a:
    env_file: ".env"
    container_name: service-a
    build:
      context: .
    environment:
      SERVICE_PORT: "8081"
      WEATHER_SERVICE_URL: "http://service-b:8082"
      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
      SERVICE_NAME: "service-a"
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - otel-collector
      - zipkin-client

  service-b:
    env_file: ".env"
    container_name: service-b
    build:
      context: .
    environment:
      SERVICE_PORT: "8082"
      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
      SERVICE_NAME: "service-b"
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - otel-collector
      - zipkin-client